version: '3.8'

services:
  jobhubbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobhubbot
    depends_on:
      - jobhubdb
      - jubhubredis
    ports:
      - "8443:8443"
    environment:
      - ConnectionStrings__DefaultConnection=Host=jobhubdb;Port=5432;Database=JoboHubBot;User Id=postgres;Password=12345
      - ConnectionStrings__Redis=jobhubredis:6379
      - BotConfiguration__BotToken=6780512045:AAGxGfF7_EwhKKfp4CKufk2x4eZgJ15QJSY
      - BotConfiguration__HostAddress=http://nginx
      - BotConfiguration__SecretKey=qwertyuiop
      - BotConfiguration__Route=/api/bot
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8443
    networks:
      - JoboHub

  jobhubdb:
    image: postgres:16
    restart: always
    container_name: jobhubdb
    environment:
      POSTGRES_DB: JoboHubBot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - JoboHub

  jubhubredis:
    image: redis:latest
    restart: always
    container_name: jobhubredis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - JoboHub

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx/default:/etc/nginx/conf.d/default
      - certbot-etc:/etc/letsencrypt
      - ./certbot/webroot:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - jobhubbot
    command: ["nginx", "-g", "daemon off;"]

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./certbot/webroot:/var/www/html
    depends_on:
      - nginx
    entrypoint: ["bash", "-c"]
    command: |
      certbot certonly --webroot -w /var/www/html --agree-tos --non-interactive -d job.sarvarbekabduqodirov.uz

volumes:
  data:
  redis-data:
  certbot-etc:

networks:
  JoboHub:
    driver: bridge
