version: '3.8'

services:
  jobhubbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobhubbot
    depends_on:
      - jobhubdb
      - jobhubredis
    ports:
      - "8443:8443"
    environment:
      - ConnectionStrings__DefaultConnection=Host=jobhubdb;Port=5433;Database=JoboHubBot;User Id=postgres;Password=12345
      - ConnectionStrings__Redis=jobhubredis:6379
      # Consider using Docker secrets for sensitive information like API tokens
      - BotConfiguration__BotToken=6780512045:AAGxGfF7_EwhKKfp4CKufk2x4eZgJ15QJSY
      - BotConfiguration__HostAddress=https://job.sarvarbekabduqodirov.uz:8443 # Adjust if port mapping for nginx changes
      - BotConfiguration__SecretKey=qwertyuiop # Use Docker secrets for this too
      - BotConfiguration__Route=/api/bot
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:8443
    networks:
      - jobohub_network

  jobhubdb:
    image: postgres:16
    restart: always
    container_name: jobhubdb
    environment:
      POSTGRES_DB: JoboHubBot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5434"
    volumes:
      - jobhubdb_data:/var/lib/postgresql/data
    networks:
      - jobohub_network

  jobhubredis:
    image: redis:latest
    restart: always
    container_name: jobhubredis
    ports:
      - "6375:6379"
    volumes:
      - jobhubredis_data:/data
    networks:
      - jobohub_network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "443:8443" # Changed host port to avoid conflict with jobhubbot
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - jobhubbot
    networks:
      - jobohub_network

volumes:
  jobhubdb_data:
  jobhubredis_data:

networks:
  jobohub_network:
    driver: bridge

# Define separate file for complete HTTPS configuration with recommended security settings
# Refer to my previous suggestions for details