version: '3.8'

services:
  jobhubbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobhubbot
    restart: always
    depends_on:
      - jobhubdb
      - jobhubredis
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=jobhubdb;Port=5432;Database=JoboHubBot;User Id=sarvar;Password=12345;Pooling=true;SSL Mode=Prefer;Trust Server Certificate=True;
      - ConnectionStrings__Redis=jobhubredis:6379
      - BotConfiguration__BotToken=6780512045:AAGxGfF7_EwhKKfp4CKufk2x4eZgJ15QJSY
      - BotConfiguration__HostAddress=https://job.sarvarbekabduqodirov.uz
      - BotConfiguration__SecretKey=qwertyuiop
      - BotConfiguration__Route=/api/bot
    networks:
      - jobohub_network

  jobhubdb:
    image: postgres:16.1
    restart: always
    container_name: jobhubdb
    environment:
      POSTGRES_DB: JoboHubBot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - jobhubdb_data:/var/lib/postgresql/data
    networks:
      - jobohub_network

  jobhubredis:
    image: redis:latest
    restart: always
    container_name: jobhubredis
    ports:
      - "6379:6379"
    volumes:
      - jobhubredis_data:/data
    networks:
      - jobohub_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - jobhubbot
    networks:
      - jobohub_network

volumes:
  jobhubdb_data:
  jobhubredis_data:

networks:
  jobohub_network:
    driver: bridge