version: '3.8'

services:
  jobhubbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobhubbot
    depends_on:
      - jobhubdb
      - jobhubredis
    ports:
      - "443:443"
    environment:
      - ConnectionStrings__DefaultConnection=Host=jobhubdb;Port=5433;Database=JoboHubBot;User Id=postgres;Password=12345
      - ConnectionStrings__Redis=jobhubredis:6379
      - BotConfiguration__BotToken=6780512045:AAGxGfF7_EwhKKfp4CKufk2x4eZgJ15QJSY
      - BotConfiguration__HostAddress=https://job.sarvarbekabduqodirov.uz
      - BotConfiguration__SecretKey=qwertyuiop
      - BotConfiguration__Route=/api/bot
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=443
    networks:
      - jobohub_network

  jobhubdb:
    image: postgres:16
    restart: always
    container_name: jobhubdb
    environment:
      POSTGRES_DB: JoboHubBot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"  # Corrected port mapping
    volumes:
      - jobhubdb_data:/var/lib/postgresql/data
    networks:
      - jobohub_network

  jobhubredis:
    image: redis:latest
    restart: always
    container_name: jobhubredis
    ports:
      - "6375:6379"
    volumes:
      - jobhubredis_data:/data
    networks:
      - jobohub_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - /etc/letsencrypt:/etc/letsencrypt  # Mount SSL certificates as a volume
    depends_on:
      - jobhubbot
    networks:
      - jobohub_network


volumes:
  jobhubdb_data:
  jobhubredis_data:

networks:
  jobohub_network:
    driver: bridge
