version: '3.8'

services:
  jobhubbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobhubbot
    depends_on:
      - jobhubdb
      - jobhubredis
    ports:
      - "8443:443"
    environment:
      - ConnectionStrings__DefaultConnection=Host=jobhubdb;Port=5432;Database=JoboHubBot;User Id=postgres;Password=12345
      - ConnectionStrings__Redis=jobhubredis:6379
      - BotConfiguration__BotToken=6780512045:AAGxGfF7_EwhKKfp4CKufk2x4eZgJ15QJSY
      - BotConfiguration__HostAddress=https://job.sarvarbekabduqodirov.uz
      - BotConfiguration__SecretKey=qwertyuiop
      - BotConfiguration__Route=/api/bot
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8443
    networks:
      - jobohub_network

  jobhubdb:
    image: postgres:16
    restart: always
    container_name: jobhubdb
    environment:
      POSTGRES_DB: JoboHubBot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - jobhubdb_data:/var/lib/postgresql/data
    networks:
      - jobohub_network

  jobhubredis:
    image: redis:latest
    restart: always
    container_name: jobhubredis
    ports:
      - "6379:6379"
    volumes:
      - jobhubredis_data:/data
    networks:
      - jobohub_network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - jobhubbot

volumes:
  jobhubdb_data:
  jobhubredis_data:

networks:
  jobohub_network:
    driver: bridge
